# Generated by Django 3.2.5 on 2021-07-09 14:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches_and_ranks', '0002_auto_20210709_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='mmr',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='rank',
            name='rank',
            field=models.CharField(default='UNRANKED', max_length=100),
        ),
    ]
