# Generated by Django 3.2.5 on 2021-07-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches_and_ranks', '0007_match_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamematchmaking',
            name='task_id',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
