# Generated by Django 3.2.5 on 2021-07-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches_and_ranks', '0008_gamematchmaking_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='league_num',
            field=models.IntegerField(default=1),
        ),
    ]
