# Generated by Django 3.2.5 on 2021-07-10 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matches_and_ranks', '0009_alter_rank_league_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamematchmaking',
            old_name='task_id',
            new_name='task_cancel_id',
        ),
        migrations.AddField(
            model_name='gamematchmaking',
            name='task_start_id',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='gamematchmaking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
