# Generated by Django 3.2.5 on 2021-07-10 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matches_and_ranks', '0010_auto_20210710_0249'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMatchMakingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=100)),
                ('is_playing', models.BooleanField(default=False)),
                ('is_searching', models.BooleanField(default=False)),
                ('task_start_id', models.CharField(max_length=300, null=True)),
                ('task_cancel_id', models.CharField(max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='Game',
            new_name='UserGameRegister',
        ),
        migrations.DeleteModel(
            name='GameMatchMaking',
        ),
    ]
